Push to charmhub track based on push to a branch

diff --git a/.github/workflows/build-bundle.yaml b/.github/workflows/build-bundle.yaml
--- a/.github/workflows/build-bundle.yaml
+++ b/.github/workflows/build-bundle.yaml
@@ -16,6 +16,20 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
+      - name: Determine Channel
+        env:
+            BRANCH: ${{ github.event.ref }}
+        run: |
+            BRANCH=${BRANCH#refs/heads/}  # strip off refs/heads/ if it exists
+            if [[ "${BRANCH}" == "main" ]]; then
+              echo "CHANNEL=latest/edge" >> "$GITHUB_ENV"
+            elif [[ "${BRANCH}" =~ ^release-[0-9]+\.[0-9]+$ ]]; then
+              echo "CHANNEL=${BRANCH:8}/edge" >> "$GITHUB_ENV"
+            else
+              echo "::error Failed to determine track/risk from branch ${BRANCH}"
+              exit 1
+            fi
+
       - name: Pack Bundle
         run: |
           sudo snap install charmcraft --classic --channel latest/stable
@@ -28,6 +42,6 @@ jobs:
         with:
           charm-path: main
           built-charm-path: ${{ env.BUNDLE_FILE }}
-          channel: latest/edge
+          channel: ${{ env.CHANNEL }}
           credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
           github-token: "${{ secrets.GITHUB_TOKEN }}"
